### PR TITLE
Feauture fixing bugs

### PR DESCRIPTION
**Pull request by pernillasterner**
1. Adding error message to search bar
2. Make total time dynamic and update recipe data with total minutes.
3. Make the first letter in cuisine uppercase

### CODE REVIEW

**Comment by NellaMori** [comment]
hi Pernilla, do you want to ditch the other PR? YOo can delete it, please link the deployed version - edit PR template with it :)

**Comment by pernillasterner** [comment]
Sorry, I was not supposed to push these changes to the Technigo branch. I will submit a pull request as soon as I finish fixing the filter function. :)

**Comment by NellaMori** [comment]
that's okay, just make sure to have the branch to be approved open, close any duplicates/old ones :)

**Comment by pernillasterner** [comment]
Closing this pull request.

**Pull request closed without merging**
